# Generated by Django 3.0.5 on 2020-12-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_author'),
        ('document_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='selected_files',
            field=models.ManyToManyField(to='project.ProjectFile'),
        ),
    ]
